from function.attendance import *
from function.bmi import *
from function.enhance import *
from function.imti import *
from function.msgCleanup import *
from function.secretCode import *
from function.study import *
from function.voting import *
from function.leveling import *
from function.Channel import *
