from function.attendance.py import *
from function.bmi.py import *
from function.enhance.py import *
from function.imti import *
from function.msgCleanup import *
from function.secretCode import *
from function.study import *
from function.voting import *
from function.leveling import *
from function.Channel import *
